### ISSUE TITLE
meta_search conflicts

### ISSUE THREAD

**Issue by holden** [texticle/texticle#9]
I use the active_admin gem and noticed it conflicts with texticle as they both use the search method and it breaks as a result.  I read in a few places about similar problems involving solr where they were able to user an alternative method solr_search but I found no such luck using texticle.  

NoMethodError (undefined method `relation' for []:ActiveRecord::Relation):

Any possible fixes?  Thanks

**Comment by ecin** [comment]
Do you need both #search methods available on the same model?

**Comment by holden** [comment]
Yes, I have one main model which would use both.  ;-(

**Comment by benhamill** [comment]
What does `active_admin`'s search method do, out of curiosity?

**Comment by holden** [comment]
Well it uses the meta_search gem https://github.com/ernie/meta_search

It creates filters by "providing methods that allow you to build up search conditions against that model"

**Comment by spilliton** [comment]
I'm wanting to use this gem, but am hesitating because I also use active_admin.  Maybe could have a configuration option for re-naming the method?  I know kaminari does this to prevent name clashes if people are also using will_paginate, seems like a decent pattern:  https://github.com/gregbell/active_admin/wiki/How-to-work-with-will_paginate

**Comment by spilliton** [comment]
Did a little more digging on this.  Meta search actually tries to account for this by defining it's method as metasearch.  It then aliases it to search if search isn't already defined:
https://github.com/ernie/meta_search/blob/master/lib/meta_search/searches/active_record.rb#L46

So I tried moving texticle above activeadmin in my Gemfile, however, after adding some debug statements in my local metasearch above the aforementioned line, it looks like :search isn't defined at the time the meta search gem loads.  I'm guessing this is because meta_search monkey patches active record at load time, while texticle uses a railtie:

https://github.com/texticle/texticle/blob/master/lib/texticle/rails.rb  

vs.

https://github.com/ernie/meta_search/blob/master/lib/meta_search.rb

**Comment by benhamill** [comment]
Yeah. I think you're right about the load order. Also, I'm not sure if switching the order of gems in the Gemfile actually changes their load order. In any case, it would be nice to figure out a solution that avoids making users worry about load order. I'm still thinking about this one. In general, I feel like mimicking kaminari is a good idea, but texticle doesn't have any meaningful configuration, so... meditating. Thanks for all the links, y'all.

**Comment by benhamill** [comment]
@holden @spilliton Would you guys mind giving current master a try to see if it fixes your issue? I recently merged a branch that implements 3 searching methods and each has its own name (`basic_search`, `advanced_search` and `fuzzy_search`). The original `search` method still exists and is basically just an alias for `advanced_search` (which is the same functionality as the current release), but you should be able to get to it with the different name. Is that enough to dodge the issues y'all're having, or does the fact that `search` is defined at all cause them problems?

**Comment by spilliton** [comment]
Nice!  I think that may have done it.  I added the following to my gemfile:

`gem 'texticle', :git => "git://github.com/texticle/texticle.git", :require => 'texticle/rails'`

After a bundle install I tried searching on my active admin pages and that seemed to work fine.  I then did the following on my Artist model, and everything also seemed to work great on quick inspection:

``` ruby
Artist.basic_search('Beck')
Artist.search('Beck')
Artist.method(:search).source_location
#returned => ["/Users/kloeppingzd/Sites/Compare-Vinyl/passenger/ruby/1.9.1/bundler/gems/texticle-a7bd9bee5647/lib/texticle.rb", 14] 
```

@holden, did it clear things up for you too?

**Comment by benhamill** [comment]
Seems fixed in master. Next release should get it.
